### ISSUE TITLE
Text editor input not supported in MacOS 

### ISSUE THREAD

**Issue by Brilator** [nfdi4plants/arcCommander#43]
I get the following error upon testing e.g. `arc i create`, `arc i person register`: 

> could not parse query: No such file or directory 

I guess the default Mac text editor is not linked correctly? 

System info:
macOS Big Sur (11.3.1)

**Comment by Brilator** [comment]
Addition: 

1. Works:
```
arc i person list
```

2. Does not work (without further parameters) and throws the same "could not parse query" error: 
```
arc i person get
arc i person update
arc i person register
```

**Comment by HLWeil** [comment]
Hey @Brilator, the reason for some commands failing and other working is simple but unfortunately yet missing in the documentation:

The editor is opened in 2 scenarios:  
1. When a command is executed and a `mandatory argument` is missing
2. When an `edit` command is executed (If a specific item has to be the target for editing, e.g. assays, then the first case might be triggered first)

`arc i person list` does not have any mandatory arguments, therefore it won't trigger the editor query even if you execute it without any arguments given
In the other cases you mentioned here, case 1. gets triggered

**Comment by HLWeil** [comment]
Also thank you very much for your feedback regarding this issue. This initial ArcCommander program is still too windows-centered, which will be definitely fixed with further progression of the installation procedure. 

I still think your problem might be fixed by some flexibility the ArcCommander provides:
You can use the `arc config set` command to edit the editor locally.

E.g.: 
`arc config set -n general.editor -v "C:\Program Files (x86)\Notepad++\notepad++.exe"`
will change the editor of a specific `arc` to be the one provided after `-v`

If you also use the `-g` flag, this will change the editor path for your `ArcCommander` installation, which therefore applies to any `arc` you create

**Comment by Brilator** [comment]
Tried `arc config set -g -n general.editor -v "/System/Applications/TextEdit.app"`. 
Now I get the error 
> could not parse query: The FileName property should not be a directory unless UseShellExecute is set.

**Comment by HLWeil** [comment]
A [stackoverflow answer](https://stackoverflow.com/a/15457975) suggests, that under macOS, the executables themselves are actually files inside a folder with the `.app` extension.

Maybe you could try one of the following paths instead:
"/Applications/TextEdit.app/Contents/MacOS/TextEdit"
"/System/Applications/TextEdit.app/Contents/MacOS/TextEdit"

**Comment by Brilator** [comment]
Yes right, I forgot about that. The issue remains nonetheless after `arc config set -g -n general.editor -v "/System/Applications/TextEdit.app/Contents/MacOS/TextEdit"`. 

Honestly, it's not a big deal for now. I wouldn't want to add via editor anyways.

**Comment by Brilator** [comment]
I'll just leave this here for the sake of completeness. 
I tried to use arc commander with different text editors: just changed the config and then ran `arc i person edit` in between. 

arc config set -g -n general.editor -v "/System/Applications/TextEdit.app/Contents/MacOS/TextEdit"
-> TextEdit app tries to open the .arc/*yml, but for some reason I don't have write permissions (also doesn't change, when adapting the permissions manually). 
-> Upon quitting TextEdit, terminal outputs proper arc error "Mandatory arguments were not given either via cli or editor prompt." 

arc config set -g -n general.editor -v "/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron"
arc config set -g -n general.editor -v "/Applications/Sublime\ Text.app/Contents/MacOS/Sublime\ Text"

-> Error message: "could not parse query: No such file or directory"

arc config set -g -n general.editor -v "/Applications/BBEdit.app/Contents/MacOS/BBEdit"
-> Heureka! Opens BBEdit with the proper .yml (although with a few AppleScript warnings that I cannot follow yet)
-> Upon typing in "Doe" and "John", saving and quitting, the next person detail .yml launches fine via BBEdit (yes, reached level 2!)
-> However, no matter if I do or don't edit the second layer, after quitting I get the error message: "could not parse query: Error: file was corrupted in Edtior"

Btw, there's a typo in the last error.

**Comment by Brilator** [comment]
One more addition. 
With **BBEdit** as the editor, I can `arc a add`, add the assay info, save&quit and it triggers the proper dir creation for the assay.
